### ISSUE TITLE
Experiencing issues parsing the xbrl

### ISSUE THREAD

**Issue by akallon1** [exitplanner/xbrl-parser#23]
I get an error when I run:
const { parseXbrlFile } = require('xbrl-parser');
const xbrl = parseXbrlFile('xbrl.xml');

or

const { CvrParser, parseAnnualReport } = require('xbrl-parser');
const report = parseAnnualReport('xbrl.xml', new CvrParser());
console.log(report);

error:
throw new Error('xbrlRootNotFound: Could not find xbrl root in the file');
^

Error: xbrlRootNotFound: Could not find xbrl root in the file

The file I am using is the exact same file you have here:
tests_/fixtures/report1.xml

Could you assist?

**Comment by dlebech** [comment]
@akallon1 the library expects a string with the full XML contents -- not a filename. I realize now that the naming of the function and documentation could be better. I have now updated the README to clarify that the parameter is not a filename but a full xml string.

So in your case, if you're using Node, you should use the `fs` module or some other way to load the contents first:

```javascript
import fs from 'fs';
import { CvrParser, parseAnnualReport } from 'xbrl-parser';
console.log(parseAnnualReport(fs.readFileSync('xbrl.xml', 'utf-8'), new CvrParser()));
```

I hope this helps.

**Comment by akallon1** [comment]
@dlebech Thank You! It now works.
